name: eva
channels:
  - nvidia
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=*=*cuda12.1*
  - pytorch-cuda=12.1
  - pytorch3d
  - pip
  - pip:
      - torch==2.1.1
      - torchvision==0.16.1
      - torchaudio==2.1.1
      - -e preprocess/hamer/third-party/ViTPose
      - third_party/diff-gaussian-rasterization
      - third_party/simple-knn
      - --upgrade https://github.com/unlimblue/KNN_CUDA/releases/download/0.2/KNN_CUDA-0.2-py3-none-any.whl
      - third_party/torch-mesh-isect
      - third_party/neural_renderer
      - --no-deps git+https://github.com/nghorbani/human_body_prior.git@cvpr19
      - git+https://github.com/facebookresearch/detectron2.git
      - smplx
      - onnxruntime
      - plyfile
      - lpips==0.1.4
      - configargparse
      - pytorch-lightning==1.9.0
      - pyrender
      - timm
      - einops
      - webdataset
      - -r requirements.txt
      - ninja
#   - mediapipe
#   - opencv-python
#   - wandb